In [2]:
t = 'He is a string. Who are you?'
print(t.capitalize())
print(t.split())
print(t.find('i'))
print(t.find('in'))
print(t.find('Python'))
print(t[0:4])
print(t.replace(' ', '|'))

w = 'http://www.google.com'
print(w.strip('http://'))


He is a string. who are you?
['He', 'is', 'a', 'string.', 'Who', 'are', 'you?']
3
11
-1
He i
He|is|a|string.|Who|are|you?
www.google.com


In [6]:
l = [1,2,3.14,'data']
print(type(l))
l.append([4,3])
print(l)
l.extend(['delta',5,6])
print(l)
l.insert(3,'beta')
print(l)
l.remove('data')
print(l)
print(l[4][1])

<class 'list'>
[1, 2, 3.14, 'data', [4, 3]]
[1, 2, 3.14, 'data', [4, 3], 'delta', 5, 6]
[1, 2, 3.14, 'beta', 'data', [4, 3], 'delta', 5, 6]
[1, 2, 3.14, 'beta', [4, 3], 'delta', 5, 6]
3


In [8]:
x = [1,2,3,4]
y = x
y[0] = 5
print(x)            #注意改y也会改x

x = [1,2,3,4]
z = x.copy()
z[0] = 5
print(x)

[5, 2, 3, 4]
[1, 2, 3, 4]


赋值上的区别

mutable – 可变
可变对象可以在其 id() 保持固定的情况下改变其取值
immutable – 不可变
具有固定值的对象。不可变对象包括数字、字符串和元组。这样的对象不能被改变。如果必须存储一个不同的值，则必须创建新的对象。它们在需要常量哈希值的地方起着重要作用，例如作为字典中的键。整数对象也是immutable

如果我们有一个可变对象 (list, dict, set 等等)，我们可以使用某些特定的操作来改变它，所有指向它的变量都会显示它的改变。

如果我们有一个不可变对象 (str, int, tuple 等等)，所有指向它的变量都将显示相同样的值，但凡是会改变这个值的操作将总是返回一个新对象



In [1]:
a = [[1,2,3,4],[1,2,3,4],[1,2,3]]
print(a)
print(a[0][3])          # Multidimensional list is not a matrix

[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3]]
4


In [4]:
a = [2,16,54]
b = []
if a[0]<a[1] and a[0]<a[2] :
    b.append(a[0])
    if a[1]<a[2]:
        b.append(a[1])
        b.append(a[2])
    else:
        b.append(a[2])
        b.append(a[1])
print(a)
print(b)

[2, 16, 54]
[2, 16, 54]


In [7]:
for i in range(2,10,3):
    print(i)
    l = i**2
    print(l)

a = 10
sumup=0
while a<100:
    a+=1
    sumup+=a
print(sumup)

2
4
5
25
8
64
4995


In [8]:
for i in range(300,351):
    if i % 17 == 0 :
        print(i)
        break
    else:
        continue

306


In [9]:
for i in range(10):
    print(i)
    for j in range(5):
        print(j)

0
0
1
2
3
4
1
0
1
2
3
4
2
0
1
2
3
4
3
0
1
2
3
4
4
0
1
2
3
4
5
0
1
2
3
4
6
0
1
2
3
4
7
0
1
2
3
4
8
0
1
2
3
4
9
0
1
2
3
4


In [12]:
x = range(1,100,2)
print(x)
print(x[5])
print(sum(x))

range(1, 100, 2)
11
2500


In [14]:

a = 1
b = 2
c = MaxOfTwo(a,b)
print(c)

def MaxOfTwo(x1,x2):
    if x1 >= x2:
        return x1
    else:
        return x2


2


In [17]:
def f(x,y):
    if x>=y:
        return (x,y)
    else:
        return (y,x)

a, b = f(1,2)
print(a,b)


2 1


In [26]:
file = open('newfile.txt','w')
file.write('I am created for the course. \n')
file.write('How about you? ')
file.write('How is your exam?')
file.close()

file = open('newfile.txt','r')
# print(file.read())

print(file.read(10))

print(file.readline())

#print(file.readlines())

file.close()









I am creat
ed for the course. 



注意这里读的时候是连续的，下一个接着上一个的末尾读

In [27]:
file = open('newfile.txt','r')
for line in file:
    print(line)
file.close()

I am created for the course. 

How about you? How is your exam?


In [33]:
file = open('newfile.txt','a')
file.write('\n I am back again. \n')
file.write('Do you miss me? \n')
file.close()

with open('newfile.txt','r') as f:
    for line in f:
        print(line)


I am created for the course. 

How about you? How is your exam?





 I am back again. 

Do you miss me? 



In [35]:
def my_sort(x):
    for i in range(0,len(x)):
        max = i
        for j in range(i,len(x)):
            if x[j] > x[max]:
                max = j
        temp = x[max]
        x[max] = x[i]
        x[i] = temp
    return x

x = [8,2,4,6,1,9,0,3,5,7]
y = my_sort(x)
print(y)


[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [37]:
import timeit

def fun(x,y):
    return x**2+y**3
t_start = timeit.default_timer()
z = fun(109.2,367.1)
t_end = timeit.default_timer()
cost = t_end-t_start
print("%f" %cost)


0.000092


In [39]:
import numpy as np

np.array([2,3,6,7])
np.array([2,3,6,7.])
np.array([2,3,6,7+1j])


array([2.+0.j, 3.+0.j, 6.+0.j, 7.+1.j])

与list不同，narray类型的元素必须是统一type的

In [42]:
np.arange(5)
np.arange(10,100,20,dtype=float)
np.linspace(0.,2.5,5)




array([0.   , 0.625, 1.25 , 1.875, 2.5  ])

In [44]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
a








[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
import numpy as np 
a = np.arange(0,20,1)
print(a)
b = a.reshape((4,5))
print(b)
c = a.reshape((20,1))
print(c)
d = a.reshape((-1,4))
print(d)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [48]:
import numpy as np
a = np.array([1,2,3,4,5])
b = a.copy()

c1 = np.dot(np.transpose(a),b)
print(c1)
c2 = np.dot(a,np.transpose(b))
print(c2)
print(a.size)
print(b.size)





55
55
5
5
