# Numpy 100道练习题

#### 1

In [1]:
import numpy as np

#### 2

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python/Ana\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python/Ana\\Library\\i

#### 3

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4

In [5]:
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5

In [11]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6

In [12]:
 z = np.zeros(10)
 z[4] = 1
 z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7

In [15]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


附：np.arange的效率要比range高很多很多

In [16]:
% timeit [i**2 for i in range(1000)]

525 µs ± 8.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit a = np.arange(1000) ** 2

5.01 µs ± 788 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 8

In [19]:
z = np.arange(10)
print(z)
z = z[::-1]
print(z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9

In [23]:
z = np.arange(0,9).reshape(3,3)
print(z)
z = np.arange(0,9).reshape(3,3).T
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### 10

In [25]:
z = np.array([1,2,0,0,4,0])
z.nonzero()


(array([0, 1, 4], dtype=int64),)

#### 11

In [26]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12

In [32]:
z = np.random.random((3,4,2))
print(z)
z = np.random.rand(3,3)
print(z)

[[[0.80969034 0.87867174]
  [0.36645558 0.11391886]
  [0.16884471 0.53690377]
  [0.76627542 0.84712889]]

 [[0.15740997 0.64190573]
  [0.08046629 0.51164402]
  [0.48275486 0.23481075]
  [0.87616629 0.45586561]]

 [[0.84387868 0.41215137]
  [0.27816139 0.53303842]
  [0.78620859 0.74439437]
  [0.05723595 0.55532523]]]
[[0.49599958 0.7647487  0.46768985]
 [0.27746484 0.02054804 0.55062228]
 [0.32095204 0.2109341  0.60389853]]


#### 13

In [33]:
z = np.random.random((10,10))
print(z.max())
print(z.min())

0.9923566252444393
0.04030713119986773


#### 14

In [34]:
z = np.random.random((10))
z.mean()

0.445619457667697

#### 15

In [35]:
z = np.ones((5,5))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16

In [2]:
import numpy as np
z = np.ones((5,5))
m = np.pad(z,(1,1),mode='constant')
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17

In [5]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(np.allclose(0.3,3*0.1))

nan
False
False
True
False
True


#### 18

In [6]:
print(np.diag(np.arange(1,5),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19

In [7]:
z = np.zeros((8,8))
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20

In [8]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21

In [9]:
unit = np.array([[0,1],[1,0]])
z = np.tile(unit,(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22

In [11]:
z = np.random.random((5,5))
z = (z-z.mean())/z.std()
z

array([[ 0.75382922, -0.9102566 , -1.01298581, -1.50787814, -0.37415548],
       [ 1.58299241,  0.2622532 ,  0.4743291 ,  0.96960838,  0.52865181],
       [-0.9836459 , -0.12306003,  0.99561833,  0.10224378, -1.18872785],
       [ 1.43740979,  0.37019992, -0.30320829,  1.00256908, -0.55854349],
       [ 1.14406313, -1.56914046, -0.8458781 ,  1.39630478, -1.6425928 ]])

#### 23

In [12]:
color = np.dtype([('r',np.ubyte,1),
                ('g',np.ubyte,1),
                ('b',np.ubyte,1),
                ('a',np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24

In [2]:
import numpy as np
z = np.dot(np.ones((5,3)), np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25

In [3]:
z = np.arange(10)
z[(z>3)&(z<8)] *= -1
z

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26

In [7]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))


9
10


#### 27

In [8]:
z = np.arange(10)
z ** z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [9]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [10]:
z < -z

array([False, False, False, False, False, False, False, False, False,
       False])

In [11]:
1j * z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [12]:
z / 1 / 1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 28

In [13]:
np.array(0)/np.array(0)

nan

In [14]:
np.array(0) // np.array(0)

0

In [16]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29

In [18]:
import numpy as np
z = np.random.uniform(-10,10,10)
z

array([ 3.30786074, -5.17558958,  0.54108139,  2.22996591,  5.35639352,
       -6.32721663, -3.16160919,  0.07205667, -8.64464816,  4.22176255])

In [19]:
np.copysign(np.ceil(np.abs(z)),z)

array([ 4., -6.,  1.,  3.,  6., -7., -4.,  1., -9.,  5.])

#### 30

In [20]:
np.lookfor("common values")

Search results for 'common values'
----------------------------------
numpy.ma.intersect1d
    Returns the unique elements common to both arrays.
numpy.gcd
    Returns the greatest common divisor of ``|x1|`` and ``|x2|``
numpy.lcm
    Returns the lowest common multiple of ``|x1|`` and ``|x2|``
numpy.intersect1d
    Find the intersection of two arrays.
numpy.ma.common_fill_value
    Return the common filling value of two masked arrays, if any.
numpy.sign
    Returns an element-wise indication of the sign of a number.
numpy.sqrt
    Return the non-negative square-root of an array, element-wise.
numpy.equal
    Return (x1 == x2) element-wise.
numpy.choose
    Construct an array from an index array and a set of arrays to choose from.
numpy.divmod
    Return element-wise quotient and remainder simultaneously.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nditer
    Efficient multi-dimensional iterator object to iterate over arrays.
numpy.arctan2
    E

In [21]:
np.info(np.intersect1d)

intersect1d(*args, **kwargs)

Find the intersection of two arrays.

Return the sorted, unique values that are in both of the input arrays.

Parameters
----------
ar1, ar2 : array_like
    Input arrays. Will be flattened if not already 1D.
assume_unique : bool
    If True, the input arrays are both assumed to be unique, which
    can speed up the calculation.  Default is False.
return_indices : bool
    If True, the indices which correspond to the intersection of the two
    arrays are returned. The first instance of a value is used if there are
    multiple. Default is False.

    .. versionadded:: 1.15.0

Returns
-------
intersect1d : ndarray
    Sorted 1D array of common and unique elements.
comm1 : ndarray
    The indices of the first occurrences of the common values in `ar1`.
    Only provided if `return_indices` is True.
comm2 : ndarray
    The indices of the first occurrences of the common values in `ar2`.
    Only provided if `return_indices` is True.


See Also
--------
numpy.l

In [22]:
z1 = np.arange(-5,5)
z2 = np.arange(10)
np.intersect1d(z1,z2)

array([0, 1, 2, 3, 4])

#### 32

In [23]:
np.sqrt(-1) , np.emath.sqrt(-1)

(nan, 1j)

#### 33

In [27]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
yesterday

numpy.datetime64('2020-03-16')

#### 34

In [28]:
z = np.arange('2020-07','2020-08',dtype='datetime64[D]')
z

array(['2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04',
       '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08',
       '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12',
       '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16',
       '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20',
       '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24',
       '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28',
       '2020-07-29', '2020-07-30', '2020-07-31'], dtype='datetime64[D]')

#### 35

In [30]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

np.add(A,B,out=B)
np.divide(A,2,out = A)
np.negative(A,out=A)
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

#### 36

In [31]:
z = np.random.uniform(0,10,10)
z - z % 1

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [32]:
np.floor(z)

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [33]:
np.ceil(z)-1

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

In [34]:
z.astype(int)

array([5, 0, 4, 4, 2, 8, 7, 5, 4, 4])

In [35]:
np.trunc(z)

array([5., 0., 4., 4., 2., 8., 7., 5., 4., 4.])

#### 37

In [43]:
z = np.zeros((5,5))
z += np.arange(5)
z





array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38

In [46]:
def gen():
    for i in range(10):
        yield i

z  = np.fromiter(gen(),dtype=float,count=-1)
z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39

In [50]:
z = np.linspace(0,1,11,endpoint=False)[1:]
z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40

In [52]:
z = np.random.randn(10)
z.sort()
z

array([-1.6552821 , -0.99145467, -0.18294898, -0.09287297, -0.07464609,
        0.2687804 ,  0.62201559,  0.7494757 ,  1.08838784,  1.20495656])

#### 41

In [53]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42

In [55]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.allclose(A,B)

False

#### 43

In [56]:
z = np.zeros(10)
print(z.flags)
z.falgs.writeable = False
z[0] = 1

C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



AttributeError: 'numpy.ndarray' object has no attribute 'falgs'

#### 44

In [73]:
z = np.random.rand(10,2)
x, y = z[:,0],z[:,1]
r = np.sqrt(x**2+y**2)
theta = np.arctan2(y,x)
r,theta


(10,) [0.640552   0.40220108 0.15075893 0.0214264  0.88909563 0.96863461
 0.70578968 0.2906305  0.58586418 0.10099881]


(array([0.73945832, 0.96441919, 0.39314068, 0.82361759, 1.02618115,
        1.16209918, 0.70789449, 0.80360402, 0.5951493 , 0.32527883]),
 array([1.04763673, 0.43018581, 0.39355412, 0.02601792, 1.0479712 ,
        0.98545122, 1.49366262, 0.37004656, 1.39392305, 0.31571813]))

#### 45

In [76]:
z = np.random.rand(10)
print(z)
z[z.argmax()] = 0
z

[0.54685878 0.39452653 0.0316379  0.32191533 0.80199042 0.06636017
 0.43588428 0.16549305 0.3699599  0.65410473]


array([0.54685878, 0.39452653, 0.0316379 , 0.32191533, 0.        ,
       0.06636017, 0.43588428, 0.16549305, 0.3699599 , 0.65410473])

#### 46

In [83]:
z = np.zeros((5,5),[('x',float),('y',float)])
z = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

#### 47

In [84]:
x = np.arange(8)
y = x+0.5
C = np.subtract.outer(x,y)
C

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [85]:
np.linalg.det(C)

1.8457040860738383e-92

#### 48

In [88]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype}: min={info.min}, max = {info.max}")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype}: min={info.min}, max ={info.max}")

<class 'numpy.int8'>: min=-128, max = 127
<class 'numpy.int16'>: min=-32768, max = 32767
<class 'numpy.int32'>: min=-2147483648, max = 2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max = 9223372036854775807
<class 'numpy.float16'>: min=-65504.0, max =65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max =3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max =1.7976931348623157e+308


#### 49

In [89]:
z = np.ones((10,10))
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 50 

In [90]:
z = np.random.uniform(0,1,10)
x = 0.5
index = np.abs(z-x).argmin()
print(index)
z[index]

2


0.3363890940306137

#### 51

In [92]:
z = np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52

In [5]:
import numpy as np
z = np.random.rand(10,2)
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)
d

array([[0.        , 0.48679789, 0.6459849 , 0.43792857, 0.80568662,
        0.2726381 , 0.16159064, 0.46906422, 0.59369554, 0.32918498],
       [0.48679789, 0.        , 0.16288193, 0.26507374, 0.33619888,
        0.63855064, 0.52084409, 0.24042145, 0.56842052, 0.40703463],
       [0.6459849 , 0.16288193, 0.        , 0.3397451 , 0.17790449,
        0.79971556, 0.68343353, 0.30081787, 0.6773889 , 0.55619996],
       [0.43792857, 0.26507374, 0.3397451 , 0.        , 0.43754206,
        0.67786109, 0.54827328, 0.04281356, 0.76981922, 0.54175831],
       [0.80568662, 0.33619888, 0.17790449, 0.43754206, 0.        ,
        0.97474064, 0.8559579 , 0.39473346, 0.84321092, 0.73407464],
       [0.2726381 , 0.63855064, 0.79971556, 0.67786109, 0.97474064,
        0.        , 0.12960343, 0.70094605, 0.46187433, 0.2841979 ],
       [0.16159064, 0.52084409, 0.68343353, 0.54827328, 0.8559579 ,
        0.12960343, 0.        , 0.57145954, 0.46166515, 0.22271217],
       [0.46906422, 0.24042145, 0.3008178

#### 53

In [6]:
z = np.zeros(10,dtype=np.float32)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [8]:
z = z.astype(np.int32,copy=False)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 54

In [9]:
from io import StringIO
s = StringIO("1, 2, 3, 4, 5\n 6,  ,  , 7, 8\n ,  , 9,10,11\n")
z = np.genfromtxt(s, delimiter=",", missing_values=' ')
z

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55

In [11]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print(index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56

In [12]:
X, Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0,0.0
G = np.exp(-(D-mu)**2/(2.0 * sigma **2))
G

array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

#### 57

In [15]:
n = 5
p = 3
z = np.zeros((n,n))
np.put(z,np.random.choice(range(n*n),p),1)
print(np.random.choice(range(n*n),p))
z

[ 5 12  8]


array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 58

In [16]:
z = np.arange(10).reshape(2,5)
z_new = z-z.mean(axis=1,keepdims=True)
z_new

array([[-2., -1.,  0.,  1.,  2.],
       [-2., -1.,  0.,  1.,  2.]])

#### 59

In [17]:
z = np.random.randint(0,10,(3,3))
print(z)
z[z[:,1].argsort(),]

[[5 9 3]
 [5 6 5]
 [0 7 3]]


array([[5, 6, 5],
       [0, 7, 3],
       [5, 9, 3]])

#### 60