# Numpy 100道练习题

#### 1

In [1]:
import numpy as np

#### 2

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python/Ana\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/python/Ana\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/python/Ana\\Library\\i

#### 3

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4

In [5]:
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


#### 5

In [11]:
import numpy
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6

In [12]:
 z = np.zeros(10)
 z[4] = 1
 z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7

In [15]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


附：np.arange的效率要比range高很多很多

In [16]:
% timeit [i**2 for i in range(1000)]

525 µs ± 8.36 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit a = np.arange(1000) ** 2

5.01 µs ± 788 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 8

In [19]:
z = np.arange(10)
print(z)
z = z[::-1]
print(z)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


#### 9

In [23]:
z = np.arange(0,9).reshape(3,3)
print(z)
z = np.arange(0,9).reshape(3,3).T
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


#### 10

In [25]:
z = np.array([1,2,0,0,4,0])
z.nonzero()


(array([0, 1, 4], dtype=int64),)

#### 11

In [26]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12

In [32]:
z = np.random.random((3,4,2))
print(z)
z = np.random.rand(3,3)
print(z)

[[[0.80969034 0.87867174]
  [0.36645558 0.11391886]
  [0.16884471 0.53690377]
  [0.76627542 0.84712889]]

 [[0.15740997 0.64190573]
  [0.08046629 0.51164402]
  [0.48275486 0.23481075]
  [0.87616629 0.45586561]]

 [[0.84387868 0.41215137]
  [0.27816139 0.53303842]
  [0.78620859 0.74439437]
  [0.05723595 0.55532523]]]
[[0.49599958 0.7647487  0.46768985]
 [0.27746484 0.02054804 0.55062228]
 [0.32095204 0.2109341  0.60389853]]


#### 13

In [33]:
z = np.random.random((10,10))
print(z.max())
print(z.min())

0.9923566252444393
0.04030713119986773


#### 14

In [34]:
z = np.random.random((10))
z.mean()

0.445619457667697

#### 15

In [35]:
z = np.ones((5,5))
z[1:-1,1:-1] = 0
z

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16

In [ ]:
z = np.ones((5,5))
